Repository Puh00/finman-api, pull requests merged in 2021-04, with the labels that each got.

#2 Backend/error handling
  backend/src/main/java/net/finman/controller/InvoiceController.java
  backend/src/main/java/net/finman/dao/InvoiceDao.java
  backend/src/main/java/net/finman/dao/InvoiceDaoImpl.java
  backend/src/main/java/net/finman/exception/ErrorDetails.java
  backend/src/main/java/net/finman/exception/ErrorHandler.java
  backend/src/main/java/net/finman/exception/ResourceNotCreatedException.java
  backend/src/main/java/net/finman/service/InvoiceService.java
  backend/src/main/java/net/finman/service/InvoiceServiceImpl.java
Labels: documentation, enhancement

#5 Update database schema and test values
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  documents/Database/schema.pdf
Labels: bug, enhancement

#8 CRUD request support for product catalogue
  backend/src/main/java/net/finman/controller/ProductController.java
  backend/src/main/java/net/finman/dao/InvoiceDaoImpl.java
  backend/src/main/java/net/finman/dao/ProductDao.java
  backend/src/main/java/net/finman/dao/ProductDaoImpl.java
  backend/src/main/java/net/finman/exception/ErrorHandler.java
  backend/src/main/java/net/finman/exception/ResourceNotDeletedException.java
  backend/src/main/java/net/finman/exception/ResourceNotFoundException.java
  backend/src/main/java/net/finman/exception/ResourceNotUpdatedException.java
  backend/src/main/java/net/finman/mapper/ProductMapper.java
  backend/src/main/java/net/finman/model/Item.java
  backend/src/main/java/net/finman/service/ProductService.java
  backend/src/main/java/net/finman/service/ProductServiceImpl.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: enhancement
